# Generated by Django 4.2 on 2026-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ENTERPRISE_ADMIN', 'Enterprise Admin'), ('DEALER_PRINCIPAL', 'Dealer Principal'), ('GENERAL_MANAGER', 'General Manager'), ('SALES_MANAGER', 'Sales Manager'), ('SALES_EXECUTIVE', 'Sales Executive'), ('SERVICE_MANAGER', 'Service Manager'), ('SERVICE_ADVISOR', 'Service Advisor'), ('TECHNICIAN', 'Technician'), ('FINANCE_OFFICER', 'Finance Officer'), ('INSURANCE_OFFICER', 'Insurance Officer')], default='SERVICE_ADVISOR', max_length=50),
        ),
    ]
