# Generated by Django 4.2 on 2026-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('L1', 'L1 — Junior / Trainee'), ('L2', 'L2 — Experienced / Certified'), ('L3', 'L3 — Master / Specialist')], help_text='Technician skill tier for job assignment matching', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('ENTERPRISE_ADMIN', 'Enterprise Admin'), ('DEALER_PRINCIPAL', 'Dealer Principal'), ('GENERAL_MANAGER', 'General Manager'), ('OEM_USER', 'OEM User'), ('SALES_MANAGER', 'Sales Manager'), ('SERVICE_MANAGER', 'Service Manager'), ('FLEET_MANAGER', 'Fleet Manager'), ('PARTS_MANAGER', 'Spare Parts Manager'), ('SALES_EXECUTIVE', 'Sales Consultant'), ('CRM_EXECUTIVE', 'CRM Executive'), ('SERVICE_ADVISOR', 'Service Advisor'), ('INSURANCE_EXECUTIVE', 'Insurance Executive'), ('FINANCE_OFFICER', 'Finance Executive'), ('TECHNICIAN', 'Technician'), ('VEHICLE_OWNER', 'Vehicle Owner')], default='SERVICE_ADVISOR', max_length=50),
        ),
    ]
