# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dealership_name', models.CharField(blank=True, max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('pan', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('default_labour_rate_per_hour', models.DecimalField(decimal_places=2, default=850.0, max_digits=10)),
                ('business_hours_start', models.TimeField(default='09:00:00')),
                ('business_hours_end', models.TimeField(default='18:30:00')),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('service_reminder_days', models.IntegerField(default=180)),
                ('insurance_renewal_reminder_days', models.IntegerField(default=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organization')),
            ],
        ),
    ]
