# Generated by Django 4.2 on 2026-09-10 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_businesssettings_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBranchChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('checklist_type', models.CharField(choices=[('OPENING', 'Morning Opening Huddle (8:30–10:00 AM)'), ('CLOSING', 'Evening Closing Reconciliation (6:00–7:30 PM)'), ('MIDDAY', 'Midday Operational Audit')], default='OPENING', max_length=20)),
                ('department', models.CharField(choices=[('SALES', 'New & Used Car Sales'), ('SERVICE', 'After-Sales & Workshop'), ('PARTS', 'Spare Parts & Warehousing'), ('FINANCE_INSURANCE', 'Finance & Insurance'), ('FACILITY', 'Facility & Dealership Security')], default='SALES', max_length=30)),
                ('items', models.JSONField(default=list, help_text='List of checklist items with status, notes, verified_by')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Sign-Off'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Fully Completed'), ('FLAGGED', 'Critical Items Flagged')], default='PENDING', max_length=20)),
                ('signed_off_by', models.CharField(blank=True, max_length=150)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('critical_issues_count', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_checklists', to='organization.branch')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailybranchchecklist',
            index=models.Index(fields=['organization_id', 'date'], name='organizatio_organiz_acc39d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybranchchecklist',
            index=models.Index(fields=['organization_id', 'status'], name='organizatio_organiz_011e42_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybranchchecklist',
            index=models.Index(fields=['organization_id', 'checklist_type', 'department'], name='organizatio_organiz_0578d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybranchchecklist',
            unique_together={('organization_id', 'branch', 'date', 'checklist_type', 'department')},
        ),
    ]
