# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vin', models.CharField(db_index=True, max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(default='PETROL', max_length=50)),
                ('transmission_type', models.CharField(default='MANUAL', max_length=50)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit from OEM'), ('RECEIVED', 'Received at Yard'), ('AVAILABLE', 'Available for Sale'), ('RESERVED', 'Reserved (Quotation Active)'), ('ALLOCATED', 'Allocated to Customer Booking'), ('PDI_IN_PROGRESS', 'Pre-Delivery Inspection In Progress'), ('PDI_PASSED', 'PDI Passed - Ready for Delivery'), ('DELIVERED', 'Delivered to Customer'), ('RETURNED', 'Returned to OEM / Transferred')], default='AVAILABLE', max_length=50)),
                ('yard_location', models.CharField(blank=True, max_length=100)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('allocated_sales_rep', models.CharField(blank=True, max_length=150)),
                ('pdi_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('DCT', 'Dual Clutch'), ('AMT', 'AMT'), ('EV_DIRECT', 'EV Direct Drive')], default='MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization_id', 'vin'], name='vehicles_ve_organiz_f3398e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization_id', 'registration_number'], name='vehicles_ve_organiz_16dcbf_idx'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='allocated_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_stock', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='vehiclestock',
            index=models.Index(fields=['organization_id', 'status'], name='vehicles_ve_organiz_cd1c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestock',
            index=models.Index(fields=['organization_id', 'vin'], name='vehicles_ve_organiz_ea2c1c_idx'),
        ),
    ]
