# Generated by Django 4.2 on 2026-09-09 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclestock_vehicle_engine_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overall_score', models.IntegerField(default=100, help_text='Aggregate health score 0-100')),
                ('engine_score', models.IntegerField(default=100)),
                ('transmission_score', models.IntegerField(default=100)),
                ('brake_score', models.IntegerField(default=100)),
                ('battery_score', models.IntegerField(default=100)),
                ('electrical_score', models.IntegerField(default=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk - Optimal Operation'), ('MEDIUM', 'Medium Risk - Service Attention Recommended'), ('HIGH', 'High Risk - Service Required Soon'), ('CRITICAL', 'Critical Risk - Immediate Workshop Visit Needed')], default='LOW', max_length=20)),
                ('active_dtc_codes', models.JSONField(blank=True, default=list, help_text='Array of active OBD-II Diagnostic Trouble Codes')),
                ('last_telemetry_at', models.DateTimeField(blank=True, null=True)),
                ('next_service_due_km', models.IntegerField(blank=True, null=True)),
                ('next_service_due_date', models.DateField(blank=True, null=True)),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='Prescriptive AI maintenance actions')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehiclehealth',
            index=models.Index(fields=['organization_id', 'risk_level'], name='vehicles_ve_organiz_ea2133_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehealth',
            index=models.Index(fields=['organization_id', 'overall_score'], name='vehicles_ve_organiz_57b947_idx'),
        ),
    ]
