# Generated by Django 4.2 on 2026-08-19 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_card_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('INSPECTION', 'Inspection In Progress'), ('ESTIMATE_PENDING', 'Estimate Pending Approval'), ('IN_PROGRESS', 'Work In Progress'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=50)),
                ('promised_delivery', models.DateTimeField(blank=True, null=True)),
                ('customer_complaints', models.TextField(blank=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
