# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclestock_vehicle_engine_number_and_more'),
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        ('workshop', '0001_initial'),
        ('inventory', '0002_purchaseorder_purchaseorderitem_stockmovement_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('ENGINE', 'Engine & Oil System'), ('BRAKES', 'Brake Pads & Discs'), ('BATTERY', 'Battery Health & Voltage'), ('TYRES', 'Tyre Tread & Alignment'), ('ELECTRICAL', 'Lighting & Electronics'), ('SUSPENSION', 'Suspension & Steering'), ('AC', 'Air Conditioning & Cabin Filter'), ('BODY', 'Bodywork & Paint'), ('SAFETY', 'Seatbelts & Airbags')], default='ENGINE', max_length=50)),
                ('item_name', models.CharField(default='Component Inspection', max_length=150)),
                ('status', models.CharField(choices=[('PASS', 'Pass (Healthy)'), ('ATTENTION', 'Needs Attention Soon'), ('REPAIR_REQUIRED', 'Immediate Repair Required'), ('CRITICAL', 'Critical Safety Hazard')], default='PASS', max_length=50)),
                ('observation', models.CharField(blank=True, max_length=255)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCardLabour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_name', models.CharField(default='General Inspection & Repair', max_length=255)),
                ('standard_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=850.0, max_digits=10)),
                ('total_labour_cost', models.DecimalField(decimal_places=2, default=850.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCardPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_requested', models.IntegerField(default=1)),
                ('quantity_issued', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advisor_name', models.CharField(default='Service Advisor', max_length=150)),
                ('odometer_in', models.IntegerField(default=0)),
                ('fuel_level', models.CharField(default='50%', max_length=20)),
                ('exterior_damage_notes', models.TextField(blank=True)),
                ('belongings_left_in_vehicle', models.TextField(blank=True)),
                ('customer_complaints', models.TextField(blank=True)),
                ('is_job_card_created', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspector_name', models.CharField(default='QC Inspector', max_length=150)),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('overall_health_score', models.IntegerField(default=100)),
                ('summary_recommendations', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_parts_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='allocated_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='workshop.workshopbay'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='workshop.technician'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='final_total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('INSPECTION', 'Inspection In Progress'), ('ESTIMATE_PENDING', 'Estimate Pending Approval'), ('APPROVED', 'Customer Approved'), ('IN_PROGRESS', 'Work In Progress'), ('WAITING_PARTS', 'Waiting for Spare Parts'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=50),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['organization_id', 'status'], name='service_job_organiz_0c9f41_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['organization_id', 'job_card_number'], name='service_job_organiz_b9d249_idx'),
        ),
        migrations.AddField(
            model_name='serviceinspection',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='service.jobcard'),
        ),
        migrations.AddField(
            model_name='servicecheckin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_checkins', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='servicecheckin',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_checkins', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_consumed', to='service.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_card_usages', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='jobcardlabour',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_items', to='service.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcardlabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_tasks', to='workshop.technician'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.serviceinspection'),
        ),
    ]
