# Generated by Django 4.2 on 2026-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_inspectionitem_jobcardlabour_jobcardpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='ai_diagnosis',
            field=models.JSONField(blank=True, default=dict, help_text='AI diagnosis payload {primary_fault, confidence, parts[], labour_hrs, root_cause}'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='digital_gate_pass_code',
            field=models.CharField(blank=True, help_text='Secure OTP/QR string for vehicle exit gate', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='nps_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='nps_score',
            field=models.IntegerField(blank=True, help_text='Net Promoter Score 1 to 10', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='required_skill_tier',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='L1', max_length=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='whatsapp_stage_notified',
            field=models.IntegerField(default=0, help_text='Last milestone stage 1 to 6 sent to customer WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['organization_id', 'required_skill_tier'], name='service_job_organiz_36f497_idx'),
        ),
    ]
