# Generated by Django 4.2 on 2026-09-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerconsent_and_more'),
        ('vehicles', '0003_vehiclehealth_and_more'),
        ('workshop', '0003_technician_active_jobs_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_jobcard_ai_diagnosis_jobcard_digital_gate_pass_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='complaint_text',
            field=models.TextField(blank=True, help_text='Direct customer/voice complaint text'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_voice_url',
            field=models.CharField(blank=True, help_text='S3 path to voice complaint recording', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='insurance_claim_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='labour_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='parts_used',
            field=models.JSONField(blank=True, default=list, help_text='[{part_id, name, qty, unit_price, total}]'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_job_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='stage_timestamps',
            field=models.JSONField(blank=True, default=dict, help_text='{received_at, started_at, qc_at, ready_at, delivered_at}'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warranty_claim_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RECEIVED', 'Vehicle Received'), ('CHECKED_IN', 'Checked In'), ('INSPECTION', 'Inspection In Progress'), ('ESTIMATE_PENDING', 'Estimate Pending Approval'), ('APPROVED', 'Customer Approved'), ('WORK_STARTED', 'Work Started'), ('IN_PROGRESS', 'Work In Progress'), ('WAITING_PARTS', 'Waiting for Spare Parts'), ('QC', 'Quality Control'), ('QUALITY_CHECK', 'Quality Check'), ('READY', 'Ready for Delivery'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=50),
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('oem_name', models.CharField(default='OEM', max_length=80)),
                ('fault_code', models.CharField(help_text='OBD/DTC Diagnostic Fault Code e.g. P0300', max_length=50)),
                ('causal_part_name', models.CharField(max_length=200)),
                ('causal_part_number', models.CharField(max_length=100)),
                ('parts_claimed', models.JSONField(blank=True, default=list)),
                ('standard_labour_hours', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('flat_rate_operation_code', models.CharField(default='FRM-STD-01', max_length=50)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Claim Prepared'), ('SUBMITTED', 'Submitted to OEM Portal'), ('APPROVED', 'OEM Approved'), ('REJECTED', 'OEM Rejected / Query Raised'), ('SETTLED', 'Credit Note Issued & Settled')], default='DRAFT', max_length=30)),
                ('oem_rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='service.jobcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAppointmentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('estimated_duration_minutes', models.IntegerField(default=90)),
                ('service_type', models.CharField(default='PERIODIC_SERVICE', max_length=50)),
                ('customer_notes', models.TextField(blank=True)),
                ('booking_channel', models.CharField(choices=[('ONLINE', 'Online Customer Portal'), ('WHATSAPP', 'WhatsApp AI Bot'), ('PHONE', 'Phone / Inbound Call'), ('WALK_IN', 'Walk In Customer')], default='WHATSAPP', max_length=30)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed via WhatsApp'), ('REMINDED_24H', 'Reminded 24h Prior'), ('REMINDED_2H', 'Reminded 2h Prior'), ('CHECKED_IN', 'Checked In / Job Card Created'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=30)),
                ('no_show_risk_score', models.FloatField(default=0.12, help_text='AI Predicted probability of no-show 0.0 to 1.0')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('allocated_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='workshop.workshopbay')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='workshop.technician')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_appointments', to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='QualityChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspector_name', models.CharField(default='Quality Controller', max_length=150)),
                ('checks', models.JSONField(default=list, help_text='List of QC check items with pass/fail and photo proof')),
                ('defects_found', models.JSONField(blank=True, default=list)),
                ('all_checks_passed', models.BooleanField(default=False)),
                ('road_test_completed', models.BooleanField(default=False)),
                ('road_test_km', models.IntegerField(default=5)),
                ('customer_signoff_obtained', models.BooleanField(default=False)),
                ('signoff_timestamp', models.DateTimeField(blank=True, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklists', to='service.jobcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='serviceappointmentschedule',
            index=models.Index(fields=['organization_id', 'scheduled_time'], name='service_ser_organiz_94a15b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointmentschedule',
            index=models.Index(fields=['organization_id', 'status'], name='service_ser_organiz_c5b14f_idx'),
        ),
    ]
