# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_inspectionitem_jobcardlabour_jobcardpart_and_more'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbay',
            name='current_job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_bay_allocation', to='service.jobcard'),
        ),
    ]
