# Generated by Django 4.2 on 2026-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_workshopbay_current_job_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='active_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technician',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technician',
            name='max_concurrent_jobs',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technician',
            name='skill_tier',
            field=models.CharField(choices=[('L1', 'Level 1 — Periodic Service, Lubes, Filters & Inspection'), ('L2', 'Level 2 — Brakes, Suspension, Steering, Electrical & AC'), ('L3', 'Level 3 — Engine Overhaul, Transmission & EV High-Voltage Powertrain')], default='L1', max_length=10),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['organization_id', 'skill_tier'], name='workshop_te_organiz_0da03d_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['organization_id', 'is_available'], name='workshop_te_organiz_27ccf0_idx'),
        ),
    ]
