# Generated by Django 4.2 on 2026-09-10 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_jobcard_complaint_text_jobcard_complaint_voice_url_and_more'),
        ('workshop', '0003_technician_active_jobs_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('REPAIR', 'Mechanical Repair'), ('DIAGNOSIS', 'Diagnostic / Scanning'), ('MAINTENANCE', 'Periodic Maintenance (PMS)'), ('INSPECTION', 'PDI / Final Quality Inspection'), ('IDLE_PARTS', 'Idle — Waiting for Spare Parts'), ('IDLE_APPROVAL', 'Idle — Waiting for Customer Approval'), ('IDLE_BAY', 'Idle — Bay Obstruction / Delay'), ('TRAINING', 'OEM Certified Training'), ('MEETING', 'Morning Huddle / Meeting')], default='MAINTENANCE', max_length=30)),
                ('flat_rate_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Sold/Standard Flat-rate Hours', max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual Clocked Hours', max_digits=6)),
                ('idle_reason', models.CharField(blank=True, max_length=150)),
                ('is_comeback', models.BooleanField(default=False, help_text='Repeat repair / Customer comeback rework')),
                ('comeback_notes', models.TextField(blank=True)),
                ('ai_efficiency_flag', models.CharField(choices=[('OPTIMAL', 'Optimal Performance'), ('SLOW', 'Exceeding Flat Rate Standard'), ('IDLE_SPIKE', 'Excessive Idle Time Spike'), ('COMEBACK_RISK', 'Rework Pattern Detected')], default='OPTIMAL', max_length=30)),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_time_logs', to='service.jobcard')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='workshop.technician')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTechnicianMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('available_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('clocked_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('productive_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sold_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('productivity_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('utilization_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('comeback_count', models.IntegerField(default=0)),
                ('idle_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_assessment', models.TextField(blank=True)),
                ('ai_evidence', models.JSONField(blank=True, default=dict)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='workshop.technician')),
            ],
        ),
        migrations.AddIndex(
            model_name='techniciantimelog',
            index=models.Index(fields=['organization_id', 'date'], name='workshop_te_organiz_8697e8_idx'),
        ),
        migrations.AddIndex(
            model_name='techniciantimelog',
            index=models.Index(fields=['organization_id', 'technician', 'date'], name='workshop_te_organiz_fe0f20_idx'),
        ),
        migrations.AddIndex(
            model_name='techniciantimelog',
            index=models.Index(fields=['organization_id', 'activity_type'], name='workshop_te_organiz_304de4_idx'),
        ),
        migrations.AddIndex(
            model_name='techniciantimelog',
            index=models.Index(fields=['organization_id', 'is_comeback'], name='workshop_te_organiz_0caa02_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytechnicianmetrics',
            index=models.Index(fields=['organization_id', 'date'], name='workshop_da_organiz_18f43f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytechnicianmetrics',
            index=models.Index(fields=['organization_id', 'productivity_pct'], name='workshop_da_organiz_487794_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytechnicianmetrics',
            index=models.Index(fields=['organization_id', 'efficiency_pct'], name='workshop_da_organiz_bc926f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytechnicianmetrics',
            unique_together={('organization_id', 'technician', 'date')},
        ),
    ]
