# Generated by Django 4.2 on 2026-09-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_vehiclehealth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('score_date', models.DateField(db_index=True)),
                ('overall_score', models.IntegerField(default=100, help_text='0–100 composite safety score')),
                ('harsh_braking_count', models.IntegerField(default=0)),
                ('harsh_acceleration_count', models.IntegerField(default=0)),
                ('speeding_events', models.IntegerField(default=0)),
                ('idle_minutes', models.IntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_trips', models.IntegerField(default=0)),
                ('avg_speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fuel_consumed_litres', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fuel_efficiency_kmpl', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fleet_tag', models.CharField(blank=True, db_index=True, help_text='Internal fleet identifier (e.g. FL-001)', max_length=50)),
                ('obd_device_id', models.CharField(blank=True, db_index=True, help_text='OBD-II / IoT device serial number', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active — On Road'), ('IDLE', 'Idle — Parked'), ('IN_SERVICE', 'In Workshop'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=50)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('health_score', models.IntegerField(default=100, help_text='0–100 composite health score')),
                ('fuel_level_pct', models.IntegerField(default=100, help_text='0–100 fuel level %')),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('next_service_km', models.IntegerField(default=10000)),
                ('next_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('zone_type', models.CharField(choices=[('YARD', 'Dealership Yard'), ('ROUTE', 'Approved Route Corridor'), ('RESTRICTED', 'Restricted Zone'), ('CUSTOMER', 'Customer Delivery Zone')], default='YARD', max_length=50)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.IntegerField(default=500)),
                ('polygon_coordinates', models.JSONField(blank=True, default=list, help_text='GeoJSON polygon coordinates for complex zones')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OBDTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('heading', models.IntegerField(default=0, help_text='Compass heading 0–360°')),
                ('rpm', models.IntegerField(default=0)),
                ('engine_temp_c', models.IntegerField(default=90)),
                ('fuel_level_pct', models.IntegerField(default=100)),
                ('battery_voltage', models.DecimalField(decimal_places=2, default=12.6, max_digits=5)),
                ('dtc_codes', models.JSONField(blank=True, default=list, help_text='Active OBD-II diagnostic trouble codes')),
                ('harsh_braking', models.BooleanField(default=False)),
                ('harsh_acceleration', models.BooleanField(default=False)),
                ('excessive_idle', models.BooleanField(default=False)),
                ('fleet_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='fleet.fleetvehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['organization_id', 'is_active'], name='fleet_geofe_organiz_01a614_idx'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FLEET_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_profile', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='driverscore',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverscore',
            name='fleet_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_scores', to='fleet.fleetvehicle'),
        ),
        migrations.AddIndex(
            model_name='obdtelemetry',
            index=models.Index(fields=['organization_id', 'fleet_vehicle_id', 'recorded_at'], name='fleet_obdte_organiz_b4811a_idx'),
        ),
        migrations.AddIndex(
            model_name='obdtelemetry',
            index=models.Index(fields=['organization_id', 'recorded_at'], name='fleet_obdte_organiz_ea74b0_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetvehicle',
            index=models.Index(fields=['organization_id', 'status'], name='fleet_fleet_organiz_d66384_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetvehicle',
            index=models.Index(fields=['organization_id', 'obd_device_id'], name='fleet_fleet_organiz_222140_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetvehicle',
            index=models.Index(fields=['organization_id', 'fleet_tag'], name='fleet_fleet_organiz_2b848f_idx'),
        ),
        migrations.AddIndex(
            model_name='driverscore',
            index=models.Index(fields=['organization_id', 'score_date'], name='fleet_drive_organiz_8a2a84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverscore',
            unique_together={('organization_id', 'fleet_vehicle', 'score_date')},
        ),
    ]
