# Generated by Django 4.2 on 2026-09-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTheftIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fuel_drop_litres', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fuel_drop_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vehicle_stationary', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical Theft Suspected'), ('WARNING', 'Unusual Consumption')], default='CRITICAL', max_length=30)),
                ('resolved', models.BooleanField(default=False)),
                ('fleet_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_theft_incidents', to='fleet.fleetvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FleetTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.CharField(default='Depot', max_length=200)),
                ('end_location', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('avg_speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fuel_consumed_litres', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('route_deviation_flag', models.BooleanField(default=False, help_text='Flagged if vehicle deviated > 500m from approved corridor')),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted')], default='IN_TRANSIT', max_length=30)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_trips', to=settings.AUTH_USER_MODEL)),
                ('fleet_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.fleetvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FleetMaintenanceCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_slot', models.CharField(default='OFF_PEAK_WEEKEND', max_length=50)),
                ('subsystem', models.CharField(default='GENERAL_PERIODIC', max_length=100)),
                ('estimated_vor_hours', models.IntegerField(default=4, help_text='Estimated Vehicle Off-Road hours')),
                ('preordered_parts', models.JSONField(blank=True, default=list, help_text='Parts pre-ordered from inventory 7 days prior')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30)),
                ('fleet_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='fleet.fleetvehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='fueltheftincident',
            index=models.Index(fields=['organization_id', 'resolved'], name='fleet_fuelt_organiz_842103_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltheftincident',
            index=models.Index(fields=['organization_id', 'detected_at'], name='fleet_fuelt_organiz_37eed0_idx'),
        ),
        migrations.AddIndex(
            model_name='fleettrip',
            index=models.Index(fields=['organization_id', 'status'], name='fleet_fleet_organiz_b7b721_idx'),
        ),
        migrations.AddIndex(
            model_name='fleettrip',
            index=models.Index(fields=['organization_id', 'start_time'], name='fleet_fleet_organiz_013b28_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmaintenancecalendar',
            index=models.Index(fields=['organization_id', 'scheduled_date'], name='fleet_fleet_organiz_9fbe96_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetmaintenancecalendar',
            index=models.Index(fields=['organization_id', 'status'], name='fleet_fleet_organiz_3334d7_idx'),
        ),
    ]
