# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('LEAD', 'Lead Created / Status Changed'), ('CALL', 'Voice / Phone Call'), ('MESSAGE', 'SMS / WhatsApp Sent'), ('APPOINTMENT', 'Appointment Scheduled'), ('TEST_DRIVE', 'Test Drive Completed'), ('QUOTATION', 'Quotation Issued'), ('BOOKING', 'Vehicle Booked'), ('SERVICE_CHECKIN', 'Service Check-In'), ('INSPECTION', 'Vehicle Inspection Done'), ('ESTIMATE', 'Service Estimate Generated'), ('JOB_CARD', 'Job Card Updated'), ('INVOICE', 'Invoice Generated'), ('PAYMENT', 'Payment Received'), ('DELIVERY', 'Vehicle Delivered'), ('FEEDBACK', 'Customer Feedback / NPS')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization_id', 'phone'], name='customers_c_organiz_d39d52_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization_id', 'email'], name='customers_c_organiz_d03b43_idx'),
        ),
        migrations.AddField(
            model_name='customertimeline',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='customers.customer'),
        ),
    ]
