# Generated by Django 4.2 on 2026-09-09 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('MARKETING_COMMUNICATION', 'Promotional & Marketing Campaigns'), ('SERVICE_REMINDERS', 'Periodic Service & Maintenance Alerts'), ('TELEMETRY_TRACKING', 'OBD-II & Connected Vehicle Telemetry'), ('WHATSAPP_UPDATES', 'Transactional WhatsApp Notification Flow'), ('CREDIT_ASSESSMENT', 'Loan / EMI Credit Score Assessment'), ('INSURANCE_RENEWAL', 'Insurance Policy Renewals & Quotations')], max_length=60)),
                ('is_consented', models.BooleanField(default=True)),
                ('consent_channel', models.CharField(choices=[('WEB_PORTAL', 'Customer Web Portal / OTP'), ('WHATSAPP_OPTIN', 'WhatsApp Verified Opt-In'), ('IN_PERSON_SIGNATURE', 'Digital Signature at Dealership'), ('SMS_OTP', 'SMS OTP Verification'), ('MOBILE_APP', 'Customer Mobile App')], default='WHATSAPP_OPTIN', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_version', models.CharField(default='v1.0', max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='customers.customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='customerconsent',
            index=models.Index(fields=['organization_id', 'customer', 'purpose'], name='customers_c_organiz_9facf9_idx'),
        ),
        migrations.AddIndex(
            model_name='customerconsent',
            index=models.Index(fields=['organization_id', 'is_consented'], name='customers_c_organiz_4de117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerconsent',
            unique_together={('organization_id', 'customer', 'purpose')},
        ),
    ]
