# Generated by Django 4.2 on 2026-09-10 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerconsent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('complaint_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(choices=[('SALES', 'Sales & Vehicle Delivery'), ('SERVICE', 'Workshop & Repairs'), ('PARTS', 'Spare Parts & Accessories'), ('FINANCE', 'Finance & Loan Processing'), ('INSURANCE', 'Insurance Claim / Renewal'), ('MANAGEMENT', 'Dealership Management & Facility')], default='SERVICE', max_length=30)),
                ('severity', models.CharField(choices=[('P1_CRITICAL', 'P1 — Critical (Executive Escalation, 4h SLA)'), ('P2_MAJOR', 'P2 — Major (Department Manager, 24h SLA)'), ('P3_MINOR', 'P3 — Minor (Team Lead, 48h SLA)')], default='P2_MAJOR', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Complaint Received'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('ACTION_REQUIRED', 'Corrective Action Required'), ('MANAGER_REVIEW', 'Pending Manager Review'), ('RESOLVED', 'Resolution Offered to Customer'), ('CLOSED', 'Customer Confirmed & Closed')], default='RECEIVED', max_length=30)),
                ('category', models.CharField(default='SERVICE_QUALITY', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_manager', models.CharField(blank=True, max_length=150)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('root_cause_analysis', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('csi_recovery_score', models.IntegerField(blank=True, help_text='Customer rating 1-5 after resolution', null=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['organization_id', 'status'], name='customers_c_organiz_25e129_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['organization_id', 'severity'], name='customers_c_organiz_83db95_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['organization_id', 'department'], name='customers_c_organiz_f6616e_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['organization_id', 'sla_breached'], name='customers_c_organiz_a414df_idx'),
        ),
    ]
