# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('vehicle_model', models.CharField(default='Sedan', max_length=150)),
                ('loan_amount_requested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('down_payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_tenure_months', models.IntegerField(default=60)),
                ('bank_partner', models.CharField(default='HDFC Bank', max_length=100)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=8.75, max_digits=5)),
                ('monthly_emi_estimated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Application'), ('SUBMITTED', 'Submitted to Bank'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('UNDER_REVIEW', 'Under Credit Review'), ('APPROVED', 'Loan Sanctioned / Approved'), ('REJECTED', 'Application Rejected'), ('DISBURSED', 'Loan Disbursed'), ('CANCELLED', 'Cancelled by Customer')], default='SUBMITTED', max_length=50)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('SERVICE', 'Workshop Service & Repairs'), ('VEHICLE_SALE', 'New / Used Vehicle Sale'), ('COUNTER_SALE', 'Over-The-Counter Parts Sale')], default='SERVICE', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='labour_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parts_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='SUCCESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued / Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('CARD', 'Credit / Debit Card'), ('BANK_TRANSFER', 'NEFT / RTGS / IMPS'), ('RAZORPAY', 'Online via Razorpay'), ('CHEQUE', 'Bank Cheque')], default='UPI', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization_id', 'status'], name='finance_inv_organiz_675cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization_id', 'invoice_number'], name='finance_inv_organiz_50ca8d_idx'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_applications', to='customers.customer'),
        ),
    ]
