# Generated by Django 4.2 on 2026-09-09 12:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeapplication_invoice_balance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEMIQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tenure_months', models.IntegerField(default=60)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('8.75'), max_digits=5)),
                ('calculated_monthly_emi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_interest_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_ltv_pct', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('approval_probability_score', models.IntegerField(default=85, help_text='AI Pre-Screening Probability 0-100')),
                ('pre_approved', models.BooleanField(default=False)),
                ('special_scheme_name', models.CharField(blank=True, max_length=150)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_quotes', to='finance.financeapplication')),
            ],
        ),
        migrations.AddIndex(
            model_name='bankemiquote',
            index=models.Index(fields=['organization_id', 'bank_name'], name='finance_ban_organiz_64ea21_idx'),
        ),
        migrations.AddIndex(
            model_name='bankemiquote',
            index=models.Index(fields=['organization_id', 'calculated_monthly_emi'], name='finance_ban_organiz_add651_idx'),
        ),
    ]
