# Generated by Django 4.2 on 2026-09-10 04:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankemiquote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubventionScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_name', models.CharField(max_length=150)),
                ('oem_name', models.CharField(default='Tata Motors', max_length=100)),
                ('applicable_vehicle_model', models.CharField(blank=True, max_length=100)),
                ('interest_rate_subsidy_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4)),
                ('oem_share_pct', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('dealer_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='applicant_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='bank_ack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='dealer_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='1% of disbursed loan amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='digilocker_documents',
            field=models.JSONField(blank=True, default=dict, help_text='{aadhaar: bool, pan: bool, bank_statement: bool, itr: bool}'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='digilocker_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('LINK_SENT', 'WhatsApp Link Sent'), ('AUTHENTICATED', 'Documents Verified by DigiLocker'), ('FAILED', 'Authentication Failed')], default='NOT_REQUESTED', max_length=30),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='employment_type',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self-Employed Professional'), ('BUSINESS', 'Business Owner / Partner')], default='SALARIED', max_length=50),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='existing_monthly_emi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='nach_mandate_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='nach_status',
            field=models.CharField(choices=[('PENDING', 'Pending Authorization'), ('ACTIVE', 'Active / Authenticated'), ('FAILED', 'Failed / Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='ocr_verification_result',
            field=models.JSONField(blank=True, default=dict, help_text='{name_match_score: 98, income_verified: bool, mismatches: []}'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='subvention_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='subvention_scheme_applied',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='NACHMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mandate_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('max_amount_authorized', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_AUTH', 'Pending Customer Netbanking / Aadhaar Auth'), ('ACTIVE', 'Active / Registered with NPCI'), ('FAILED', 'Authentication Failed'), ('REVOKED', 'Revoked / Cancelled')], default='PENDING_AUTH', max_length=30)),
                ('umrn_number', models.CharField(blank=True, help_text='Unique Mandate Reference Number from NPCI', max_length=50)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nach_mandates', to='finance.financeapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
