# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Supplier'), ('APPROVED', 'Manager Approved'), ('RECEIVED', 'Goods Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Goods Receipt from PO'), ('ISSUE_TO_JOBCARD', 'Issued to Job Card'), ('RETURN_FROM_JOBCARD', 'Returned from Job Card'), ('ADJUSTMENT', 'Physical Audit Adjustment'), ('SCRAPPED', 'Damaged / Scrapped')], max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('payment_terms', models.CharField(default='NET_30', max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='bin_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='part',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['organization_id', 'category'], name='inventory_p_organiz_06d975_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['organization_id', 'part_number'], name='inventory_p_organiz_06d553_idx'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier'),
        ),
    ]
