# Generated by Django 4.2 on 2026-09-11 04:53

from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable name for this key (e.g. Telematics Gateway)', max_length=150)),
                ('key_prefix', models.CharField(db_index=True, help_text='Public prefix (e.g. aek_live_8f9a)', max_length=16)),
                ('hashed_secret', models.CharField(db_index=True, help_text='SHA-256 hash of the complete key token', max_length=64)),
                ('scopes', models.JSONField(default=list, help_text='Permitted API scopes: read:telemetry, write:telemetry, read:leads, write:leads, read:service, write:jobcards')),
                ('rate_limit_rpm', models.PositiveIntegerField(default=120, help_text='Rate limit in requests per minute')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of receiving integration / webhook target', max_length=150)),
                ('target_url', models.URLField(help_text='Endpoint URL to receive HTTP POST webhooks', max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of subscribed event strings')),
                ('secret', models.CharField(default=secrets.token_hex, help_text='HMAC signing secret (32 bytes hex)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='developer.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
