# Generated by Django 4.2 on 2026-09-09 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_vehiclehealth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVBatteryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('soc_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='State of Charge 0–100%', max_digits=5)),
                ('soh_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='State of Health 0–100%', max_digits=5)),
                ('cell_voltages', models.JSONField(blank=True, default=list, help_text='Array of individual cell voltages (V)')),
                ('cell_temp_min_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cell_temp_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cell_temp_avg_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pack_voltage', models.DecimalField(decimal_places=2, default=0.0, help_text='Total pack voltage (V)', max_digits=8)),
                ('pack_current', models.DecimalField(decimal_places=2, default=0.0, help_text='Current draw/regen (A)', max_digits=8)),
                ('pack_power_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('odometer_km', models.IntegerField(default=0)),
                ('ambient_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('is_driving', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_data', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('charger_type', models.CharField(choices=[('AC_SLOW', 'AC Slow (3.3 kW)'), ('AC_NORMAL', 'AC Normal (7.4 kW)'), ('AC_FAST', 'AC Fast (22 kW)'), ('DC_FAST', 'DC Fast (50 kW)'), ('DC_ULTRA', 'DC Ultra-Fast (150+ kW)'), ('HOME', 'Home Charger')], default='AC_NORMAL', max_length=50)),
                ('status', models.CharField(choices=[('CHARGING', 'Currently Charging'), ('COMPLETED', 'Completed'), ('INTERRUPTED', 'Interrupted / Error'), ('SCHEDULED', 'Scheduled')], default='CHARGING', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('soc_start_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('soc_end_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('energy_added_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('energy_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_per_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('charge_efficiency_pct', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('charger_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('score_date', models.DateField(db_index=True)),
                ('overall_score', models.IntegerField(default=100, help_text='0–100 composite battery health')),
                ('soh_score', models.IntegerField(default=100, help_text='State of Health component (40% weight)')),
                ('cell_balance_score', models.IntegerField(default=100, help_text='Cell balance delta score (25% weight)')),
                ('thermal_score', models.IntegerField(default=100, help_text='Temperature management score (20% weight)')),
                ('charge_pattern_score', models.IntegerField(default=100, help_text='Charge behaviour score (15% weight)')),
                ('avg_soh_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('max_cell_delta_mv', models.IntegerField(default=0, help_text='Max cell voltage imbalance (mV)')),
                ('avg_temp_c', models.DecimalField(decimal_places=1, default=25.0, max_digits=5)),
                ('charge_cycles_total', models.IntegerField(default=0)),
                ('estimated_remaining_cycles', models.IntegerField(default=2000)),
                ('estimated_replacement_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_health_scores', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='evbatterydata',
            index=models.Index(fields=['organization_id', 'vehicle_id', 'recorded_at'], name='ev_evbatter_organiz_0c58a4_idx'),
        ),
        migrations.AddIndex(
            model_name='evbatterydata',
            index=models.Index(fields=['organization_id', 'recorded_at'], name='ev_evbatter_organiz_8a0599_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['organization_id', 'vehicle_id', 'started_at'], name='ev_charging_organiz_151530_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['organization_id', 'status'], name='ev_charging_organiz_bd1a06_idx'),
        ),
        migrations.AddIndex(
            model_name='batteryhealthscore',
            index=models.Index(fields=['organization_id', 'score_date'], name='ev_batteryh_organiz_6b6a40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batteryhealthscore',
            unique_together={('organization_id', 'vehicle', 'score_date')},
        ),
    ]
