# Generated by Django 4.2 on 2026-09-09 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclehealth_and_more'),
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVRangeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('current_soc_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_soh_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_remaining_range_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('nearest_charging_stations', models.JSONField(blank=True, default=list, help_text='Nearby fast chargers with live status & distances')),
                ('whatsapp_alert_sent', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ALERT_SENT', 'Alert Dispatched via WhatsApp'), ('STATION_REACHED', 'Vehicle Reached Charging Station'), ('DISMISSED', 'Dismissed by Driver')], default='ALERT_SENT', max_length=30)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_alerts', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryReplacementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_soh_pct', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('trigger_reason', models.CharField(default='SOH_DROPPED_BELOW_70_PCT', max_length=150)),
                ('options', models.JSONField(blank=True, default=list, help_text='4 options: OEM New, Refurb, Recondition, Trade-in')),
                ('selected_option', models.CharField(blank=True, max_length=50)),
                ('estimated_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('booking_status', models.CharField(choices=[('OPTIONS_PRESENTED', 'Options Presented to Customer'), ('BOOKED', 'Workshop Job Card Booked'), ('IN_PROGRESS', 'Battery Replacement in Progress'), ('COMPLETED', 'Battery Replaced / Upgraded')], default='OPTIONS_PRESENTED', max_length=30)),
                ('job_card_reference', models.CharField(blank=True, max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_replacement_plans', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='evrangealert',
            index=models.Index(fields=['organization_id', 'triggered_at'], name='ev_evrangea_organiz_b7a621_idx'),
        ),
        migrations.AddIndex(
            model_name='evrangealert',
            index=models.Index(fields=['organization_id', 'status'], name='ev_evrangea_organiz_cd8e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='batteryreplacementplan',
            index=models.Index(fields=['organization_id', 'booking_status'], name='ev_batteryr_organiz_e5d2a7_idx'),
        ),
    ]
