# Generated by Django 4.2 on 2026-08-19 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interested_vehicle_model', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('TEST_DRIVE', 'Test Drive Scheduled'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='NEW', max_length=50)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('WALK_IN', 'Walk In'), ('REFERRAL', 'Referral'), ('PHONE', 'Phone Inquiry'), ('CAMPAIGN', 'Marketing Campaign')], default='WEBSITE', max_length=50)),
                ('ai_score', models.IntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('assigned_sales_rep', models.CharField(blank=True, max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_type', models.CharField(choices=[('SALES_TEST_DRIVE', 'Sales Test Drive'), ('SERVICE_CHECKUP', 'Service Checkup'), ('FINANCE_CONSULT', 'Finance Consultation')], default='SERVICE_CHECKUP', max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
