# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclestock_vehicle_engine_number_and_more'),
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('booking_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('promised_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('ALLOCATED', 'Stock Allocated'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='CONFIRMED', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message'), ('MEETING', 'Showroom Visit'), ('EMAIL', 'Email')], default='CALL', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quotation_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('vehicle_model', models.CharField(default='SUV', max_length=150)),
                ('base_ex_showroom_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('accessories_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('registration_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('extended_warranty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_on_road_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_model', models.CharField(default='SUV', max_length=150)),
                ('sales_rep', models.CharField(default='Sales Executive', max_length=150)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=50)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interested_vehicle_model',
            field=models.CharField(default='SUV', max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WALK_IN', 'Walk In'), ('REFERRAL', 'Referral'), ('PHONE', 'Phone Inquiry'), ('CAMPAIGN', 'Marketing Campaign'), ('DIGITAL_AD', 'Digital Ad')], default='WEBSITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('TEST_DRIVE', 'Test Drive Scheduled'), ('QUOTATION', 'Quotation Issued'), ('NEGOTIATION', 'Negotiation'), ('BOOKED', 'Vehicle Booked'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='NEW', max_length=50),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'status'], name='sales_lead_organiz_0c67fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'ai_score'], name='sales_lead_organiz_f6681c_idx'),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drives', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='vehicle_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drives', to='vehicles.vehiclestock'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.vehiclestock'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='sales.quotation'),
        ),
    ]
