# Generated by Django 4.2 on 2026-09-09 12:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_booking_leadfollowup_quotation_testdrive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='escalation_level',
            field=models.IntegerField(default=0, help_text='0=Rep, 1=Team Lead, 2=Sales Mgr, 3=GM/Dealer Principal'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('HOT', 'Hot (30m SLA)'), ('WARM', 'Warm (4h SLA)'), ('COLD', 'Cold (24h SLA)')], default='WARM', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Within Rep Limits (<= 3%)'), ('PENDING_APPROVAL', 'Pending Manager Approval (> 3%)'), ('APPROVED', 'Manager / GM Approved'), ('REJECTED', 'Discount Overruled')], default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by_user',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='minimum_floor_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dealer absolute bottom floor on-road price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WALK_IN', 'Walk In'), ('REFERRAL', 'Referral'), ('PHONE', 'Phone Inquiry'), ('CAMPAIGN', 'Marketing Campaign'), ('DIGITAL_AD', 'Digital Ad'), ('WHATSAPP_BOT', 'WhatsApp Inbound Bot'), ('INSTAGRAM_DM', 'Instagram DM'), ('OEM_PORTAL', 'OEM Referral Portal')], default='WEBSITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_REQUIRED', 'Approval Required'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'priority'], name='sales_lead_organiz_52759f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'sla_deadline'], name='sales_lead_organiz_e45038_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'sla_breached'], name='sales_lead_organiz_0d0fac_idx'),
        ),
    ]
