# Generated by Django 4.2 on 2026-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_lead_escalation_level_lead_first_contact_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('AI_SCORED', 'AI Scored'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('TEST_DRIVE', 'Test Drive Scheduled'), ('TEST_DRIVE_DONE', 'Test Drive Done'), ('QUOTATION', 'Quotation Issued'), ('NEGOTIATION', 'Negotiation'), ('BOOKED', 'Vehicle Booked'), ('DELIVERED', 'Delivered'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost'), ('NURTURE_D3', 'Nurture Day 3'), ('NURTURE_D7', 'Nurture Day 7'), ('NURTURE_D14', 'Nurture Day 14'), ('WARM_ARCHIVE', 'Warm Archive'), ('SEQ_W1', 'Cold Sequence Week 1'), ('SEQ_W2', 'Cold Sequence Week 2'), ('SEQ_W3', 'Cold Sequence Week 3'), ('SEQ_W4', 'Cold Sequence Week 4'), ('COLD_ARCHIVE', 'Cold Archive'), ('RE_ENGAGEMENT_D30', 'Re-engagement 30-Day'), ('RE_ENGAGEMENT_D60', 'Re-engagement 60-Day')], default='NEW', max_length=50),
        ),
    ]
