# Generated by Django 4.2 on 2026-09-10 13:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_dailybranchchecklist_and_more'),
        ('sales', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('SALES', 'Sales'), ('SERVICE', 'Service'), ('FINANCE', 'Finance'), ('USED_CARS', 'Used Cars')], default='SALES', max_length=30)),
                ('slabs', models.JSONField(default=list, help_text='List of slab dicts: [{min_units, max_units, rate_per_unit, bonus}]')),
                ('csi_threshold', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('csi_penalty_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('GROUP', 'Group Level'), ('BRANCH', 'Branch Level'), ('TEAM', 'Team Level'), ('INDIVIDUAL_REP', 'Individual Sales Executive')], default='INDIVIDUAL_REP', max_length=20)),
                ('sales_rep_name', models.CharField(blank=True, max_length=150)),
                ('period_month', models.IntegerField(default=9)),
                ('period_year', models.IntegerField(default=2026)),
                ('target_vehicle_units', models.IntegerField(default=10)),
                ('actual_vehicle_units', models.IntegerField(default=0)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('target_accessories_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_accessories_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('target_finance_penetration_pct', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5)),
                ('actual_finance_penetration_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('target_insurance_penetration_pct', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5)),
                ('actual_insurance_penetration_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('target_csi_score', models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=5)),
                ('actual_csi_score', models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=5)),
                ('ai_predicted_units', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('gap_to_target_units', models.IntegerField(default=0)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='organization.branch')),
            ],
        ),
        migrations.CreateModel(
            name='IncentiveCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sales_rep_name', models.CharField(max_length=150)),
                ('period_month', models.IntegerField(default=9)),
                ('period_year', models.IntegerField(default=2026)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=10)),
                ('units_achieved', models.IntegerField(default=0)),
                ('achievement_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('slab_applied', models.CharField(blank=True, max_length=100)),
                ('gross_incentive', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('csi_score', models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=5)),
                ('csi_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quality_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('calculation_audit_trail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('APPROVED', 'Manager Approved'), ('DISBURSED', 'Disbursed')], default='CALCULATED', max_length=30)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='sales.incentiverule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_calculations', to='sales.salestarget')),
            ],
        ),
        migrations.AddIndex(
            model_name='salestarget',
            index=models.Index(fields=['organization_id', 'period_year', 'period_month'], name='sales_sales_organiz_001872_idx'),
        ),
        migrations.AddIndex(
            model_name='salestarget',
            index=models.Index(fields=['organization_id', 'level'], name='sales_sales_organiz_afee52_idx'),
        ),
        migrations.AddIndex(
            model_name='salestarget',
            index=models.Index(fields=['organization_id', 'achievement_percentage'], name='sales_sales_organiz_72715d_idx'),
        ),
        migrations.AddIndex(
            model_name='incentivecalculation',
            index=models.Index(fields=['organization_id', 'period_year', 'period_month'], name='sales_incen_organiz_f2d033_idx'),
        ),
        migrations.AddIndex(
            model_name='incentivecalculation',
            index=models.Index(fields=['organization_id', 'status'], name='sales_incen_organiz_86b4ca_idx'),
        ),
    ]
