# Generated by Django 4.2 on 2026-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='external_message_id',
            field=models.CharField(blank=True, help_text='Gupshup / Twilio / SendGrid tracking ID', max_length=150),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Template variables, webhook responses, deep links'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent to Gateway'), ('DELIVERED', 'Delivered'), ('READ', 'Read by Recipient'), ('FAILED', 'Delivery Failed')], default='QUEUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'status'], name='communicati_organiz_f83310_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'channel'], name='communicati_organiz_c347d8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'is_read'], name='communicati_organiz_317a2c_idx'),
        ),
    ]
