# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclestock_vehicle_engine_number_and_more'),
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('renewal_due_date', models.DateField(blank=True, null=True)),
                ('quoted_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer_contacted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Outreach'), ('QUOTED', 'Quote Sent'), ('RENEWED', 'Renewed Successfully'), ('LOST_TO_COMPETITOR', 'Lost to Competitor')], default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='provider',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='surveyor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='surveyor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insured_declared_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurer_name',
            field=models.CharField(default='HDFC ERGO', max_length=100),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_type',
            field=models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive Package'), ('THIRD_PARTY', 'Third Party Liability Only'), ('ZERO_DEP', 'Bumper-to-Bumper Zero Depreciation')], default='COMPREHENSIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring in < 30 Days'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='status',
            field=models.CharField(choices=[('FILED', 'Claim Filed / Intimated'), ('SURVEY_SCHEDULED', 'Surveyor Inspection Scheduled'), ('ESTIMATE_SUBMITTED', 'Repair Estimate Submitted'), ('APPROVED', 'Claim Approved by Insurer'), ('REJECTED', 'Claim Rejected'), ('SETTLED', 'Payment Settled')], default='FILED', max_length=50),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='policy_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['organization_id', 'expiry_date'], name='insurance_i_organiz_74d718_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['organization_id', 'status'], name='insurance_i_organiz_59917a_idx'),
        ),
        migrations.AddField(
            model_name='insurancerenewal',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='insurance.insurancepolicy'),
        ),
    ]
