# Generated by Django 4.2 on 2026-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancerenewal_remove_insurancepolicy_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='dealer_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='dealer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Gross commission % on OD premium', max_digits=5),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='ncb_percentage',
            field=models.IntegerField(default=20, help_text='No-Claim Bonus percentage (0 to 50)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='od_premium',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Own Damage premium component', max_digits=12),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='renewal_stage_notified',
            field=models.IntegerField(default=0, help_text='Last sequence day notified (90, 60, 30, or 7)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='tp_premium',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Third Party statutory premium component', max_digits=12),
        ),
        migrations.AddField(
            model_name='insurancerenewal',
            name='payment_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='insurancerenewal',
            name='projected_ncb',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='insurancerenewal',
            name='sequence_stage',
            field=models.IntegerField(default=90, help_text='90, 60, 30, or 7 days prior'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['organization_id', 'renewal_stage_notified'], name='insurance_i_organiz_047ba0_idx'),
        ),
    ]
