# Generated by Django 4.2 on 2026-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurancepolicy_dealer_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='ai_damage_assessment',
            field=models.JSONField(blank=True, default=dict, help_text="{parts_to_replace: [], repair_cost: 0, severity: 'MODERATE'}"),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='damage_photos_urls',
            field=models.JSONField(blank=True, default=list, help_text='6-angle damage inspection photos'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='ncb_loss_impact',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Projected NCB financial loss if claim processed', max_digits=10),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='replaces_surveyor',
            field=models.BooleanField(default=True, help_text='Replaces surveyor for 80% of claims'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='add_on_covers',
            field=models.JSONField(blank=True, default=list, help_text="['ZERO_DEP', 'ENGINE_PROTECT', 'RSA', 'KEY_PROTECT', 'TYRE_SECURE']"),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='autoera_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='claim_history_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='pdf_policy_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='renewal_prediction_score',
            field=models.FloatField(default=0.85, help_text='AI Renewal Propensity Score 0.0 to 1.0'),
        ),
    ]
