# Generated by Django 4.2 on 2026-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0002_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content_text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('SOP', 'Standard Operating Procedure'), ('SERVICE_MANUAL', 'OEM Technical Service Manual'), ('POLICY', 'Dealership Warranty & Service Policy'), ('PRICE_LIST', 'Official Parts & Labour Price List'), ('WARRANTY_GUIDE', 'Warranty Coverage Guidelines'), ('SALES_BROCHURE', 'Vehicle Model Sales Brochure')], default='SOP', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded / Awaiting Processing'), ('VALIDATING', 'Validating Document Structure'), ('PROCESSED', 'Chunked & Processed'), ('READY', 'Ready for RAG Retrieval'), ('ARCHIVED', 'Archived Version'), ('FAILED', 'Processing Failed')], default='UPLOADED', max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('created_by_user', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization_id', 'document_type'], name='ai_platform_organiz_5a3dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization_id', 'status'], name='ai_platform_organiz_b0d05a_idx'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_platform.knowledgedocument'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['organization_id', 'document_id'], name='ai_platform_organiz_05c519_idx'),
        ),
    ]
