# Generated by Django 4.2 on 2026-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0003_knowledgechunk_knowledgedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='text-embedding-004', max_length=100),
        ),
    ]
