# Generated by Django 4.2 on 2026-08-22 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0004_knowledgechunk_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.CharField(max_length=150)),
                ('agent_name', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=100)),
                ('parameters_json', models.JSONField(default=dict)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (Automated / Read)'), ('MEDIUM', 'Medium Risk (Standard CRM / Notes)'), ('HIGH', 'High Risk (Estimate Approvals / Parts Adjustments)'), ('CRITICAL', 'Critical Risk (Payments, Refunds, Discounts)')], default='MEDIUM', max_length=20)),
                ('reason', models.TextField()),
                ('expected_effect', models.TextField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed by Agent'), ('PENDING_APPROVAL', 'Pending Human Authorization'), ('APPROVED', 'Approved by Authorized Human'), ('REJECTED', 'Rejected by Authorized Human'), ('EXECUTED', 'Action Successfully Executed in ERP'), ('FAILED', 'Execution Failed'), ('EXPIRED', 'Proposal Expired')], default='PENDING_APPROVAL', max_length=30)),
                ('approved_by_user', models.CharField(blank=True, max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('execution_result_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prompt_name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('agent_name', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Version'), ('ARCHIVED', 'Archived Version')], default='ACTIVE', max_length=20)),
                ('created_by_user', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['organization_id', 'agent_name', 'status'], name='ai_platform_organiz_ed0a31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together={('organization_id', 'prompt_name', 'version')},
        ),
        migrations.AddIndex(
            model_name='actionproposal',
            index=models.Index(fields=['organization_id', 'status'], name='ai_platform_organiz_a97b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='actionproposal',
            index=models.Index(fields=['organization_id', 'risk_level'], name='ai_platform_organiz_1dbc6e_idx'),
        ),
    ]
