# Generated by Django 4.2 on 2026-08-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customertimeline_customer_customer_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0002_vehiclestock_vehicle_engine_number_and_more'),
        ('ai_platform', '0005_actionproposal_prompttemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('channel', models.CharField(choices=[('PHONE', 'PSTN / Telephony'), ('WEBRTC', 'WebRTC Browser Voice'), ('SIMULATOR', 'Local Voice Simulator')], default='PHONE', max_length=50)),
                ('provider', models.CharField(default='SIMULATOR', max_length=50)),
                ('provider_call_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound Call from Customer'), ('OUTBOUND', 'Outbound Campaign / Follow-up')], default='INBOUND', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Call Initiated'), ('RINGING', 'Ringing at Destination'), ('CONNECTED', 'Call Connected'), ('AI_ACTIVE', 'AI Agent Active in Conversation'), ('HUMAN_HANDOFF', 'Transferred to Human Staff'), ('COMPLETED', 'Call Completed Successfully'), ('FAILED', 'Call Failed / Network Error'), ('CANCELLED', 'Call Cancelled by Caller')], default='INITIATED', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en-IN', max_length=20)),
                ('agent_name', models.CharField(default='Service Advisor Agent', max_length=100)),
                ('transcript_reference', models.CharField(blank=True, max_length=255)),
                ('recording_reference', models.CharField(blank=True, max_length=255)),
                ('consent_status', models.BooleanField(default=True)),
                ('handoff_status', models.BooleanField(default=False)),
                ('handoff_reason', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('stt_latency_ms', models.IntegerField(default=0)),
                ('llm_latency_ms', models.IntegerField(default=0)),
                ('tts_latency_ms', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('speaker', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'AI Specialist Agent'), ('SYSTEM', 'Voice System / IVR'), ('HUMAN_STAFF', 'Human Service Advisor / Manager')], max_length=20)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('audio_offset_ms', models.IntegerField(default=0)),
                ('language', models.CharField(default='en-IN', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='ai_platform.voicesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='voicetranscript',
            index=models.Index(fields=['organization_id', 'session_id'], name='ai_platform_organiz_894375_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['organization_id', 'status'], name='ai_platform_organiz_57ea3f_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['organization_id', 'provider_call_id'], name='ai_platform_organiz_2201e6_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['organization_id', 'created_at'], name='ai_platform_organiz_cda211_idx'),
        ),
    ]
