# Generated by Django 4.2 on 2026-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0006_voicesession_voicetranscript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='gemini-embedding-2', max_length=100),
        ),
    ]
