# Generated by Django 4.2 on 2026-09-09 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0007_alter_knowledgechunk_embedding_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prediction_type', models.CharField(choices=[('LEAD_SCORE', 'Sales Lead Scoring & Conversion Probability'), ('CHURN_RISK', 'Customer Churn Prediction'), ('BATTERY_HEALTH', 'EV Battery Health & RUL Degradation Prediction'), ('COMPONENT_FAILURE', 'IoT/OBD-II Predictive Maintenance Alert'), ('INSURANCE_FRAUD', 'Insurance Claim Anomaly & Fraud Probability'), ('CREDIT_DEFAULT', 'EMI / Finance Default Risk Scoring'), ('MARGIN_GUARD', 'Discount / Price Optimization Advice'), ('SERVICE_RECOMMENDATION', 'AI Service Advisor Prescriptive Diagnosis')], max_length=60)),
                ('entity_type', models.CharField(help_text='e.g. Lead, Vehicle, Customer, Claim', max_length=60)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('prediction_data', models.JSONField(default=dict, help_text='Features, weights, SHAP explanations, outputs')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('is_validated', models.BooleanField(blank=True, help_text='Ground truth feedback', null=True)),
                ('actual_outcome', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['organization_id', 'prediction_type'], name='ai_platform_organiz_04dab6_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['organization_id', 'entity_type', 'entity_id'], name='ai_platform_organiz_bffe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['organization_id', 'confidence_score'], name='ai_platform_organiz_016b65_idx'),
        ),
    ]
